import type { ServiceDescriptor } from '@shared/types'

export const SERVICE_CATALOG: ServiceDescriptor[] = [
  { id: 'terraform', label: 'Terraform', category: 'Infrastructure', migrated: false, maturity: 'beta' },
  { id: 'overview', label: 'Overview', category: 'Catalog', migrated: true, maturity: 'production-ready' },
  { id: 'session-hub', label: 'Session Hub', category: 'Security', migrated: true, maturity: 'production-ready' },
  { id: 'compare', label: 'Compare', category: 'Security', migrated: true, maturity: 'production-ready' },
  { id: 'compliance-center', label: 'Compliance Center', category: 'Security', migrated: true, maturity: 'production-ready' },
  { id: 'ec2', label: 'EC2', category: 'Compute', migrated: false, maturity: 'beta' },
  { id: 'cloudwatch', label: 'CloudWatch', category: 'Management', migrated: true, maturity: 'production-ready' },
  { id: 's3', label: 'S3', category: 'Storage', migrated: false, maturity: 'beta' },
  { id: 'lambda', label: 'Lambda', category: 'Compute', migrated: false, maturity: 'beta' },
  { id: 'auto-scaling', label: 'Auto Scaling', category: 'Compute', migrated: false, maturity: 'beta' },
  { id: 'rds', label: 'RDS', category: 'Database', migrated: false, maturity: 'beta' },
  { id: 'cloudformation', label: 'CloudFormation', category: 'Infrastructure', migrated: false, maturity: 'beta' },
  { id: 'cloudtrail', label: 'CloudTrail', category: 'Management', migrated: true, maturity: 'production-ready' },
  { id: 'ecr', label: 'ECR', category: 'Containers', migrated: false, maturity: 'experimental' },
  { id: 'eks', label: 'EKS', category: 'Compute', migrated: false, maturity: 'beta' },
  { id: 'ecs', label: 'ECS', category: 'Containers', migrated: false, maturity: 'beta' },
  { id: 'vpc', label: 'VPC', category: 'Networking', migrated: false, maturity: 'beta' },
  { id: 'load-balancers', label: 'Load Balancers', category: 'Networking', migrated: false, maturity: 'beta' },
  { id: 'route53', label: 'Route 53', category: 'Networking', migrated: false, maturity: 'beta' },
  { id: 'security-groups', label: 'Security Groups', category: 'Security', migrated: false, maturity: 'beta' },
  { id: 'acm', label: 'ACM', category: 'Networking', migrated: false, maturity: 'beta' },
  { id: 'iam', label: 'IAM', category: 'Security', migrated: false, maturity: 'experimental' },
  { id: 'identity-center', label: 'Identity Center / SSO', category: 'Security', migrated: true, maturity: 'beta' },
  { id: 'sns', label: 'SNS', category: 'Messaging', migrated: true, maturity: 'beta' },
  { id: 'sqs', label: 'SQS', category: 'Messaging', migrated: true, maturity: 'beta' },
  { id: 'sts', label: 'STS', category: 'Security', migrated: true, maturity: 'production-ready' },
  { id: 'kms', label: 'KMS', category: 'Security', migrated: false, maturity: 'experimental' },
  { id: 'waf', label: 'WAF', category: 'Security', migrated: false, maturity: 'experimental' },
  { id: 'secrets-manager', label: 'Secrets Manager', category: 'Security', migrated: false, maturity: 'beta' },
  { id: 'key-pairs', label: 'Key Pairs', category: 'Security', migrated: false, maturity: 'beta' }
]
